# -*- coding: utf-8 -*-
"""Rodrigo_Camargo_Afrodev.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VnYYUN9yMnanGbfhXCqIpCMgtDHhauK_
"""

# importando bibliotecas
import pandas as pd
from matplotlib import pyplot as plt

#Criando os dataframe para cada base de dados
df = pd.read_excel("Athletes.xlsx") 
df1 = pd.read_excel("Coaches.xlsx") 
df2 = pd.read_excel("EntriesGender.xlsx") 
df3 = pd.read_excel("Medals.xlsx") 
df4 = pd.read_excel("Teams.xlsx")

#Menu opção para visualizar determinado dado
menu_options = { 
    1: "Total de atletas, participantes e medalhas", 
    2: "País com mais medalhas e menos medalhas", 
    3: "Lista de esportes e participantes masculino e feminino por esporte", 
    4: "Quantidade de treinadores", 
    5: "Sair", 
}

#Função que mostra o total de atletas, participantes e medalhas
def option1(): 
  totAtletas = df.set_index(["Name"])
  print("Total de atletas participantes.")
  print(len(totAtletas))
  print("\n")
  totAtletaH = df2["Male"].sum()
  print("Total de participantes homens")
  print(totAtletaH)
  print("\n")
  totAtletaM = df2["Female"].sum() 
  print("Total de participantes mulheres")
  print(totAtletaM) 
  print("\n")
  df2.insert(3, "TotEsporte", df2["Female"] + df2["Male"]) 
  print("Total de participantes por esporte")
  print(df2)
  print("\n") 
  df3.insert(5, "TotMedals", df3["Gold"] + df3["Silver"] + df3["Bronze"])
  print("Total de medalhas por país")
  print(df3)

#Função que mostra o país com mais medalhas e menos medalhas
def option2(): 
  goldMax = df3[df3.Gold == df3.Gold.max()] 
  print("País com mais medalhas de ouro")
  print(goldMax)
  print("\n")
  silverMax = df3[df3.Silver == df3.Silver.max()] 
  print("País com mais medalhas de prata")
  print(silverMax)
  print("\n")
  bronzeMax = df3[df3.Bronze == df3.Bronze.max()]
  print("País com mais medalhas de bronze")
  print(bronzeMax)
  print("\n")
  goldMin = df3[df3.Gold == df3.Gold.min()] 
  print("País com menos medalhas de ouro")
  print(goldMin.head(1)) 
  print("\n")
  silverMin = df3[df3.Silver == df3.Silver.min()]
  print("País com menos medalhas de prata")
  print(silverMin.head(1)) 
  print("\n")
  bronzeMin = df3[df3.Bronze == df3.Bronze.min()]
  print("País com menos medalhas de bronze")
  print(bronzeMin.head(1))
  print("\n")

#Função que mostra a lista de esportes e participantes masculino e feminino por esporte
def option3():
  listaEsporte = df2.iloc[:,0] 
  print("Lista com esportes participantes")
  print(listaEsporte) 
  print("\n")
  listaMaisHomem = df2[df2.Male > df2.Female] 
  print("Lista de esportes com mais homens que mulheres")
  print(listaMaisHomem) 
  print("\n")
  listaMaisMulheres = df2[df2.Female > df2.Male] 
  print("Lista de esportes com mais mulheres que homens")
  print(listaMaisMulheres) 
  print("\n")

#Função que mostra a quantidade de treinadores e quanto time por esporte cada pais tem
def option4():
  treinadorPais = df1.groupby(["NOC"]).size() 
  print("Quantidade de treinadores por país")
  print(treinadorPais)
  print("\n")
  paisMaxtreinador = df1.groupby(["NOC"]).size() 
  print("País com a maior quantidade de treinadores")
  print(paisMaxtreinador.max()) 
  print("\n")
  treinadorEsporte = df1.groupby(["Discipline"]).size() 
  print("Quantidade de treinadores por esporte")
  print(treinadorEsporte) 
  print("\n")
  timeEsporte = df1.groupby(["Discipline", "NOC"]).size()
  print("Quanto times por esporte cada país tem")
  print(timeEsporte)
  print("\n")

#Função principal e escolha da opção desejada
if __name__ == "__main__":
   while(True): 
     option = '' 
     option = int(input("Escolha os dados que queira visualizar: ")) 
     if option == 1:
        option1()
     elif option == 2: 
        option2() 
     elif option == 3:
        option3()
     elif option == 4:
        option4() 
     elif option == 5: 
        print("Saindo...") 
        break
     else: 
       print("Opção inválida. Entre com um número de 1 a 5.")

